<?php

$label_label_color_name_clone_args = [
	'label'             => 'Label/Label Color/Name',
	'name'              => 'label_label_color_name',
	'type'              => 'clone',
	'instructions'      => '',
	'required'          => 0,
	'conditional_logic' => 0,
	'wrapper'           => array(
		'width' => '',
		'class' => '',
		'id'    => '',
	),
	'clone'             => array(
		0 => 'group_57a1f652d56eb',
	),
	'display'           => 'seamless',
	'layout'            => 'block',
	'prefix_label'      => 0,
	'prefix_name'       => 0,
	'replace'           => 1,
];

$classes_id_clone_args = [
	'label'             => 'Classes/ID',
	'name'              => 'classes_id',
	'type'              => 'clone',
	'instructions'      => '',
	'required'          => 0,
	'conditional_logic' => 0,
	'wrapper'           => array(
		'width' => '',
		'class' => '',
		'id'    => '',
	),
	'clone'             => array(
		0 => 'group_57a1f7c2051ea',
	),
	'display'           => 'seamless',
	'layout'            => 'block',
	'prefix_label'      => 0,
	'prefix_name'       => 0,
	'replace'           => 1,
];

/*——————————————————————————————————————————————————————————
/  Open Row
——————————————————————————————————————————————————————————*/
#region Open Row
$open_row_layout_args                         = [
	'key'        => '563a1ba77d9fa',
	'name'       => 'layout_open_row',
	'label'      => 'Open Row',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
	),
	'min'        => '',
	'max'        => '',
];
$open_row_layout_args['sub_fields'][0]['key'] = 'field_open_row_label_label_color_name';
$open_row_layout_args['sub_fields'][1]['key'] = 'field_open_row_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Close Row
——————————————————————————————————————————————————————————*/
#region Close Row
$close_row_layout_args                         = [
	'key'        => '563a1bc37d9fb',
	'name'       => 'layout_close_row',
	'label'      => 'Close Row',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
	),
	'min'        => '',
	'max'        => '',
];
$close_row_layout_args['sub_fields'][0]['key'] = 'field_close_row_label_label_color_name';
$close_row_layout_args['sub_fields'][1]['key'] = 'field_close_row_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Open Column
——————————————————————————————————————————————————————————*/
#region Open Column
$open_column_layout_args                         = [
	'key'        => '5776c1bd32209',
	'name'       => 'layout_open_column',
	'label'      => 'Open Column',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
		array(
			'key'               => 'field_577bb5d294a03',
			'label'             => 'Inside Classes',
			'name'              => 'inside_class',
			'type'              => 'text',
			'instructions'      => 'Comma-separated list. No default. Can modified with a filter.',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
	),
	'min'        => '',
	'max'        => '',
];
$open_column_layout_args['sub_fields'][0]['key'] = 'field_open_column_label_label_color_name';
$open_column_layout_args['sub_fields'][1]['key'] = 'field_open_column_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Close Column
——————————————————————————————————————————————————————————*/
#region Close Column
$close_column_layout_args                         = [
	'key'        => '5776c29a3220e',
	'name'       => 'layout_close_column',
	'label'      => 'Close Column',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
	),
	'min'        => '',
	'max'        => '',
];
$close_column_layout_args['sub_fields'][0]['key'] = 'field_close_column_label_label_color_name';
$close_column_layout_args['sub_fields'][1]['key'] = 'field_close_column_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Content
——————————————————————————————————————————————————————————*/
#region Content
$content_layout_args                         = [
	'key'        => '5638c419fa436',
	'name'       => 'layout_content',
	'label'      => 'Content',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
		array(
			'key'               => 'field_5638c422fa437',
			'label'             => 'Content',
			'name'              => 'content',
			'type'              => 'wysiwyg',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'tabs'              => 'all',
			'toolbar'           => 'full',
			'media_upload'      => 1,
		),
	),
	'min'        => '',
	'max'        => '',
];
$content_layout_args['sub_fields'][0]['key'] = 'field_content_label_label_color_name';
$content_layout_args['sub_fields'][1]['key'] = 'field_content_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Header
——————————————————————————————————————————————————————————*/
#region Header
$header_layout_args                         = [
	'key'        => '5638c4a2fa43a',
	'name'       => 'layout_header',
	'label'      => 'Header',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
		array(
			'key'               => 'field_572944fdaf95d',
			'label'             => 'Elements',
			'name'              => 'elements',
			'type'              => 'select',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'Title'       => 'Title',
				'Subtitle'    => 'Subtitle',
				'Description' => 'Description',
				'Link'        => 'Link',
				'Background'  => 'Background',
			),
			'default_value'     => array(
				0 => 'Title',
				1 => 'Subtitle',
				2 => 'Description',
				3 => 'Link',
				4 => 'Background',
			),
			'allow_null'        => 0,
			'multiple'          => 1,
			'ui'                => 1,
			'ajax'              => 1,
			'placeholder'       => '',
			'disabled'          => 0,
			'readonly'          => 0,
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_5638c4c8fa43c',
			'label'             => 'Title',
			'name'              => 'title',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Title',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_5638c4d0fa43d',
			'label'             => 'Subtitle',
			'name'              => 'subtitle',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Subtitle',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_5638c4dafa43e',
			'label'             => 'Description',
			'name'              => 'description',
			'type'              => 'textarea',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Description',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'maxlength'         => '',
			'rows'              => 3,
			'new_lines'         => 'wpautop',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_5638c4e5fa43f',
			'label'             => 'Link',
			'name'              => 'link',
			'type'              => 'page_link',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Link',
					),
				),
			),
			'wrapper'           => array(
				'width' => '50',
				'class' => '',
				'id'    => '',
			),
			'post_type'         => array(),
			'taxonomy'          => array(),
			'allow_null'        => 0,
			'allow_archives'    => 1,
			'multiple'          => 0,
		),
		array(
			'key'               => 'field_5638c4f0fa440',
			'label'             => 'Link Text',
			'name'              => 'link_text',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Link',
					),
				),
			),
			'wrapper'           => array(
				'width' => '50',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_5728dd18127f9',
			'label'             => 'Background Type',
			'name'              => 'background_type',
			'type'              => 'radio',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Background',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'Image' => 'Image',
				'Video' => 'Video',
				'Color' => 'Color',
			),
			'other_choice'      => 0,
			'save_other_choice' => 0,
			'default_value'     => '',
			'layout'            => 'horizontal',
			'allow_null'        => 0,
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_5638c4b0fa43b',
			'label'             => 'Background Image',
			'name'              => 'background_image',
			'type'              => 'image',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728dd18127f9',
						'operator' => '==',
						'value'    => 'Image',
					),
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Background',
					),
				),
			),
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'return_format'     => 'id',
			'preview_size'      => 'thumbnail',
			'library'           => 'all',
			'min_width'         => '',
			'min_height'        => '',
			'min_size'          => '',
			'max_width'         => '',
			'max_height'        => '',
			'max_size'          => '',
			'mime_types'        => '',
		),
		array(
			'key'               => 'field_5728ddbb127fa',
			'label'             => 'MP4',
			'name'              => 'mp4',
			'type'              => 'file',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728dd18127f9',
						'operator' => '==',
						'value'    => 'Video',
					),
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Background',
					),
				),
			),
			'wrapper'           => array(
				'width' => '33.333',
				'class' => '',
				'id'    => '',
			),
			'return_format'     => 'array',
			'library'           => 'all',
			'min_size'          => '',
			'max_size'          => '',
			'mime_types'        => 'mp4',
		),
		array(
			'key'               => 'field_5728dde5127fb',
			'label'             => 'Webm',
			'name'              => 'webm',
			'type'              => 'file',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728dd18127f9',
						'operator' => '==',
						'value'    => 'Video',
					),
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Background',
					),
				),
			),
			'wrapper'           => array(
				'width' => '33.333',
				'class' => '',
				'id'    => '',
			),
			'return_format'     => 'array',
			'library'           => 'all',
			'min_size'          => '',
			'max_size'          => '',
			'mime_types'        => 'webm',
		),
		array(
			'key'               => 'field_5728ddfa127fd',
			'label'             => 'JPG',
			'name'              => 'jpg',
			'type'              => 'file',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728dd18127f9',
						'operator' => '==',
						'value'    => 'Video',
					),
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Background',
					),
				),
			),
			'wrapper'           => array(
				'width' => '33.333',
				'class' => '',
				'id'    => '',
			),
			'return_format'     => 'array',
			'library'           => 'all',
			'min_size'          => '',
			'max_size'          => '',
			'mime_types'        => 'jpg',
		),
		array(
			'key'               => 'field_5728de08127fe',
			'label'             => 'Background Color',
			'name'              => 'background_color',
			'type'              => 'color_picker',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728dd18127f9',
						'operator' => '==',
						'value'    => 'Color',
					),
					array(
						'field'    => 'field_572944fdaf95d',
						'operator' => '==',
						'value'    => 'Background',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
		),
	),
	'min'        => '',
	'max'        => '',
];
$header_layout_args['sub_fields'][0]['key'] = 'field_header_label_label_color_name';
$header_layout_args['sub_fields'][1]['key'] = 'field_header_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Slideshow
——————————————————————————————————————————————————————————*/
#region Slideshow
$slideshow_sub_fields = [
	'label_label_color_name' => $label_label_color_name_clone_args,
	'classes_id'             => $classes_id_clone_args,
	'elements'               => array(
		'key'               => 'field_5791054024d9f',
		'label'             => 'Elements',
		'name'              => 'elements',
		'type'              => 'select',
		'instructions'      => 'Controls elements for individual slides.',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => array(
			'width' => '',
			'class' => '',
			'id'    => '',
		),
		'choices'           => array(
			'Slideshow Background'   => 'Slideshow Background',
			'Slide Background'       => 'Slide Background',
			'Slide Title'            => 'Slide Title',
			'Slide Subtitle'         => 'Slide Subtitle',
			'Slide Description'      => 'Slide Description',
			'Slide Link'             => 'Slide Link',
			'Slide Foreground Image' => 'Slide Foreground Image',
		),
		'default_value'     => array(
			0 => 'Slide Foreground Image',
			2 => 'Slide Title',
			3 => 'Slide Subtitle',
			4 => 'Slide Description',
			5 => 'Slide Link',
		),
		'allow_null'        => 0,
		'multiple'          => 1,
		'ui'                => 1,
		'ajax'              => 1,
		'placeholder'       => '',
		'disabled'          => 0,
		'readonly'          => 0,
		'return_format'     => 'value',
	),
	'slideshow_background'   => array(
		'key'               => 'field_5791054024da0',
		'label'             => 'Slideshow Background',
		'name'              => 'slideshow_background',
		'type'              => 'image',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => array(
			array(
				array(
					'field'    => 'field_5791054024d9f',
					'operator' => '==',
					'value'    => 'Slideshow Background',
				),
			),
		),
		'wrapper'           => array(
			'width' => '',
			'class' => '',
			'id'    => '',
		),
		'return_format'     => 'id',
		'preview_size'      => 'medium',
		'library'           => 'all',
		'min_width'         => '',
		'min_height'        => '',
		'min_size'          => '',
		'max_width'         => '',
		'max_height'        => '',
		'max_size'          => '',
		'mime_types'        => '',
	),
	'slides'                 => array(
		'key'               => 'field_5791054024da1',
		'label'             => 'Slides',
		'name'              => 'slides',
		'type'              => 'repeater',
		'instructions'      => '',
		'required'          => 0,
		'conditional_logic' => 0,
		'wrapper'           => array(
			'width' => '',
			'class' => '',
			'id'    => '',
		),
		'collapsed'         => 'field_5791054024da2',
		'min'               => '',
		'max'               => '',
		'layout'            => 'block',
		'button_label'      => 'Add Slide',
		'sub_fields'        => array(
			array(
				'key'               => 'field_5791054024da2',
				'label'             => 'Title',
				'name'              => 'title',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Title',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5791054024da3',
				'label'             => 'Subtitle',
				'name'              => 'subtitle',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Subtitle',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5791054024da4',
				'label'             => 'Description',
				'name'              => 'description',
				'type'              => 'textarea',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Description',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => 3,
				'new_lines'         => 'wpautop',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5791054024da5',
				'label'             => 'Link',
				'name'              => 'link',
				'type'              => 'page_link',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Link',
						),
					),
				),
				'wrapper'           => array(
					'width' => 50,
					'class' => '',
					'id'    => '',
				),
				'post_type'         => array(),
				'taxonomy'          => array(),
				'allow_null'        => 0,
				'multiple'          => 0,
				'allow_archives'    => 1,
			),
			array(
				'key'               => 'field_5791054024da6',
				'label'             => 'Link Text',
				'name'              => 'link_text',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Link',
						),
					),
				),
				'wrapper'           => array(
					'width' => 50,
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5791054024da7',
				'label'             => 'Background Type',
				'name'              => 'background_type',
				'type'              => 'radio',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Background',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'Image' => 'Image',
					'Video' => 'Video',
					'Color' => 'Color',
				),
				'allow_null'        => 0,
				'other_choice'      => 0,
				'save_other_choice' => 0,
				'default_value'     => '',
				'layout'            => 'horizontal',
				'return_format'     => 'value',
			),
			array(
				'key'               => 'field_5791054024da8',
				'label'             => 'Background Image',
				'name'              => 'background_image',
				'type'              => 'image',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024da7',
							'operator' => '==',
							'value'    => 'Image',
						),
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Background',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'id',
				'preview_size'      => 'thumbnail',
				'library'           => 'all',
				'min_width'         => '',
				'min_height'        => '',
				'min_size'          => '',
				'max_width'         => '',
				'max_height'        => '',
				'max_size'          => '',
				'mime_types'        => '',
			),
			array(
				'key'               => 'field_5791054024da9',
				'label'             => 'MP4',
				'name'              => 'mp4',
				'type'              => 'file',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024da7',
							'operator' => '==',
							'value'    => 'Video',
						),
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Background',
						),
					),
				),
				'wrapper'           => array(
					'width' => '33.333',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'library'           => 'all',
				'min_size'          => '',
				'max_size'          => '',
				'mime_types'        => 'mp4',
			),
			array(
				'key'               => 'field_5791054024daa',
				'label'             => 'Webm',
				'name'              => 'webm',
				'type'              => 'file',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024da7',
							'operator' => '==',
							'value'    => 'Video',
						),
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Background',
						),
					),
				),
				'wrapper'           => array(
					'width' => '33.333',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'library'           => 'all',
				'min_size'          => '',
				'max_size'          => '',
				'mime_types'        => 'webm',
			),
			array(
				'key'               => 'field_5791054024dab',
				'label'             => 'JPG',
				'name'              => 'jpg',
				'type'              => 'file',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024da7',
							'operator' => '==',
							'value'    => 'Video',
						),
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Background',
						),
					),
				),
				'wrapper'           => array(
					'width' => '33.333',
					'class' => '',
					'id'    => '',
				),
				'return_format'     => 'array',
				'library'           => 'all',
				'min_size'          => '',
				'max_size'          => '',
				'mime_types'        => 'jpg',
			),
			array(
				'key'               => 'field_5791054024dac',
				'label'             => 'Background Color',
				'name'              => 'background_color',
				'type'              => 'color_picker',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_5791054024da7',
							'operator' => '==',
							'value'    => 'Color',
						),
						array(
							'field'    => 'field_5791054024d9f',
							'operator' => '==',
							'value'    => 'Slide Background',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
			),
			array(
				'key'               => 'field_5791054024dad',
				'label'             => 'Show/Hide',
				'name'              => 'show',
				'type'              => 'true_false',
				'instructions'      => 'Check this box to show the slide. Uncheck it to hide the slide.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => '',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_5791054024dae',
				'label'             => 'Classes',
				'name'              => 'class',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => 50,
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_5791054024daf',
				'label'             => 'ID',
				'name'              => 'id',
				'type'              => 'text',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => 50,
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
		),
	),
];
$slideshow_sub_fields = apply_filters( 'acf_flex_layouts_slideshow_sub_fields', $slideshow_sub_fields );

$slideshow_layout_args                                                = [
	'key'        => '5791054024d9b',
	'name'       => 'layout_slideshow',
	'label'      => 'Slideshow',
	'display'    => 'block',
	'sub_fields' => $slideshow_sub_fields,
	'min'        => '',
	'max'        => '',
];
$slideshow_layout_args['sub_fields']['label_label_color_name']['key'] = 'field_slideshow_label_label_color_name';
$slideshow_layout_args['sub_fields']['classes_id']['key']             = 'field_slideshow_classes_id';

$slideshow_layout_args = apply_filters( 'acf_flex_layouts_slideshow_layout_args', $slideshow_layout_args );
#endregion

/*——————————————————————————————————————————————————————————
/  Post List
——————————————————————————————————————————————————————————*/
#region Post List
$post_list_layout_args                         = [
	'key'        => '56381eafdaee1',
	'name'       => 'layout_post_list',
	'label'      => 'Post List',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
		array(
			'key'               => 'field_563b63432ae8a',
			'label'             => 'List Title',
			'name'              => 'list_title',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_5728eea4a58e0',
			'label'             => 'Data Type',
			'name'              => 'data_type',
			'type'              => 'select',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'Automatic' => 'Automatic',
				'Manual'    => 'Manual',
			),
			'default_value'     => array(),
			'allow_null'        => 0,
			'multiple'          => 0,
			'ui'                => 0,
			'ajax'              => 0,
			'placeholder'       => '',
			'disabled'          => 0,
			'readonly'          => 0,
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_56381eeddaee2',
			'label'             => 'Post Type',
			'name'              => 'post_type',
			'type'              => 'post_type_selector',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728eea4a58e0',
						'operator' => '==',
						'value'    => 'Automatic',
					),
				),
			),
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'fields[post_type'  => array(
				'select_type' => 0,
			),
			'select_type'       => 2,
		),
		array(
			'key'               => 'field_56382053daee4',
			'label'             => 'Number of Posts',
			'name'              => 'number_of_posts',
			'type'              => 'number',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728eea4a58e0',
						'operator' => '==',
						'value'    => 'Automatic',
					),
				),
			),
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'min'               => 1,
			'max'               => '',
			'step'              => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_563b624a4d01b',
			'label'             => 'Manual Posts',
			'name'              => 'manual_posts',
			'type'              => 'relationship',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728eea4a58e0',
						'operator' => '==',
						'value'    => 'Manual',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'post_type'         => array(),
			'taxonomy'          => array(),
			'filters'           => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements'          => '',
			'min'               => '',
			'max'               => '',
			'return_format'     => 'object',
		),
		array(
			'key'               => 'field_56382065daee5',
			'label'             => 'List Link',
			'name'              => 'link',
			'type'              => 'page_link',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'post_type'         => array(),
			'taxonomy'          => array(),
			'allow_null'        => 0,
			'multiple'          => 0,
			'allow_archives'    => 1,
		),
		array(
			'key'               => 'field_563820addaee6',
			'label'             => 'List Link Text',
			'name'              => 'link_text',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
	),
	'min'        => '',
	'max'        => '',
];
$post_list_layout_args['sub_fields'][0]['key'] = 'field_post_list_label_label_color_name';
$post_list_layout_args['sub_fields'][1]['key'] = 'field_post_list_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Map
——————————————————————————————————————————————————————————*/
#region Map
$map_layout_args                         = [
	'key'        => '563820c9daee7',
	'name'       => 'layout_map',
	'label'      => 'Map',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
		array(
			'key'               => 'field_5638b538fa415',
			'label'             => 'Title',
			'name'              => 'title',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => 75,
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_564205432acd0',
			'label'             => 'Zoom Level',
			'name'              => 'zoom_level',
			'type'              => 'number',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => 25,
				'class' => '',
				'id'    => '',
			),
			'default_value'     => 12,
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'min'               => 1,
			'max'               => 16,
			'step'              => 1,
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_5638b5effa416',
			'label'             => 'Markers',
			'name'              => 'markers',
			'type'              => 'repeater',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => 75,
				'class' => '',
				'id'    => '',
			),
			'min'               => '',
			'max'               => '',
			'layout'            => 'block',
			'button_label'      => 'Add Marker',
			'collapsed'         => '',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5640cc07a7ffa',
					'label'             => 'Marker',
					'name'              => 'marker',
					'type'              => 'google_map',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'center_lat'        => '',
					'center_lng'        => '',
					'zoom'              => '',
					'height'            => 200,
				),
			),
		),
		array(
			'key'               => 'field_5638b614fa417',
			'label'             => 'Options',
			'name'              => 'options',
			'type'              => 'checkbox',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => 25,
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'show_markers'     => 'Show Markers',
				'disable_controls' => 'Disable Controls',
				'allow_panning'    => 'Allow Panning',
				'allow_dragging'   => 'Allow Dragging',
				'allow_zooming'    => 'Allow Zooming',
			),
			'default_value'     => array(
				'true' => 'true',
			),
			'layout'            => 'vertical',
			'toggle'            => 0,
			'return_format'     => 'value',
		),
	),
	'min'        => '',
	'max'        => '',
];
$map_layout_args['sub_fields'][0]['key'] = 'field_map_label_label_color_name';
$map_layout_args['sub_fields'][1]['key'] = 'field_map_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Tabs
——————————————————————————————————————————————————————————*/
#region Tabs
$tabs_layout_args                         = [
	'key'        => '5638bbecfa418',
	'name'       => 'layout_tabs',
	'label'      => 'Tabs',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
		array(
			'key'               => 'field_572a3a2c946b3',
			'label'             => 'Elements',
			'name'              => 'elements',
			'type'              => 'select',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'Section Background Image' => 'Section Background Image',
				'Title'                    => 'Title',
				'Subtitle'                 => 'Subtitle',
				'Text'                     => 'Text',
				'Link'                     => 'Link',
			),
			'default_value'     => array(
				0 => 'Section Background Image',
				1 => 'Title',
				2 => 'Subtitle',
				3 => 'Text',
				4 => 'Link',
			),
			'allow_null'        => 0,
			'multiple'          => 1,
			'ui'                => 1,
			'ajax'              => 1,
			'placeholder'       => '',
			'disabled'          => 0,
			'readonly'          => 0,
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_5638bcbbfa41f',
			'label'             => 'Background Image',
			'name'              => 'background_image',
			'type'              => 'image',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572a3a2c946b3',
						'operator' => '==',
						'value'    => 'Section Background Image',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'return_format'     => 'id',
			'preview_size'      => 'thumbnail',
			'library'           => 'all',
			'min_width'         => '',
			'min_height'        => '',
			'min_size'          => '',
			'max_width'         => '',
			'max_height'        => '',
			'max_size'          => '',
			'mime_types'        => '',
		),
		array(
			'key'               => 'field_5638bbf4fa419',
			'label'             => 'Tabs',
			'name'              => 'tabs',
			'type'              => 'repeater',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'collapsed'         => 'field_5638d16ad3e54',
			'min'               => '',
			'max'               => '',
			'layout'            => 'block',
			'button_label'      => 'Add Tab',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5638d16ad3e54',
					'label'             => 'Tab Title',
					'name'              => 'tab_title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_5638bc0efa41a',
					'label'             => 'Title',
					'name'              => 'title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_572a3a2c946b3',
								'operator' => '==',
								'value'    => 'Title',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_5638bc16fa41b',
					'label'             => 'Subtitle',
					'name'              => 'subtitle',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_572a3a2c946b3',
								'operator' => '==',
								'value'    => 'Subtitle',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_5638bc20fa41c',
					'label'             => 'Text',
					'name'              => 'text',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_572a3a2c946b3',
								'operator' => '==',
								'value'    => 'Text',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'full',
					'media_upload'      => 1,
				),
				array(
					'key'               => 'field_5638bc3efa41d',
					'label'             => 'Link',
					'name'              => 'link',
					'type'              => 'url',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_572a3a2c946b3',
								'operator' => '==',
								'value'    => 'Link',
							),
						),
					),
					'wrapper'           => array(
						'width' => 50,
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_5638bc97fa41e',
					'label'             => 'Link Text',
					'name'              => 'link_text',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_572a3a2c946b3',
								'operator' => '==',
								'value'    => 'Link',
							),
						),
					),
					'wrapper'           => array(
						'width' => 50,
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_572a3a06946b2',
					'label'             => 'Show/Hide',
					'name'              => 'show',
					'type'              => 'true_false',
					'instructions'      => 'Check this box to show the slide. Uncheck it to hide the slide.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 1,
				),
				array(
					'key'               => 'field_572a3b75946b5',
					'label'             => 'Classes',
					'name'              => 'class',
					'type'              => 'text',
					'instructions'      => 'Comma-separated list.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_572a3b83946b6',
					'label'             => 'ID',
					'name'              => 'id',
					'type'              => 'text',
					'instructions'      => 'One word only.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
			),
		),
	),
	'min'        => '',
	'max'        => '',
];
$tabs_layout_args['sub_fields'][0]['key'] = 'field_tabs_label_label_color_name';
$tabs_layout_args['sub_fields'][1]['key'] = 'field_tabs_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Blurb
——————————————————————————————————————————————————————————*/
#region Blurb
$blurb_layout_args                         = [
	'key'        => '5638bd05fa420',
	'name'       => 'layout_blurb',
	'label'      => 'Blurb',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
		array(
			'key'               => 'field_572a38b8946b1',
			'label'             => 'Elements',
			'name'              => 'elements',
			'type'              => 'select',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'Image' => 'Image',
				'Icon'  => 'Icon',
				'Title' => 'Title',
				'Text'  => 'Text',
				'Link'  => 'Link',
			),
			'default_value'     => array(
				0 => 'Image',
				1 => 'Title',
				2 => 'Text',
				3 => 'Link',
			),
			'allow_null'        => 0,
			'multiple'          => 1,
			'ui'                => 1,
			'ajax'              => 1,
			'placeholder'       => '',
			'disabled'          => 0,
			'readonly'          => 0,
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_5638c0aefa42c',
			'label'             => 'Image',
			'name'              => 'foreground_image',
			'type'              => 'image',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572a38b8946b1',
						'operator' => '==',
						'value'    => 'Image',
					),
				),
			),
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'return_format'     => 'id',
			'preview_size'      => 'thumbnail',
			'library'           => 'all',
			'min_width'         => '',
			'min_height'        => '',
			'min_size'          => '',
			'max_width'         => '',
			'max_height'        => '',
			'max_size'          => '',
			'mime_types'        => '',
		),
		array(
			'key'               => 'field_5730c0cf3c06a',
			'label'             => 'Icon Name',
			'name'              => 'icon_name',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572a38b8946b1',
						'operator' => '==',
						'value'    => 'Icon',
					),
				),
			),
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_5638c303fa431',
			'label'             => 'Media Placement',
			'name'              => 'media_placement',
			'type'              => 'radio',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572a38b8946b1',
						'operator' => '==',
						'value'    => 'Image',
					),
				),
				array(
					array(
						'field'    => 'field_572a38b8946b1',
						'operator' => '==',
						'value'    => 'Icon',
					),
				),
			),
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'top'   => 'Top',
				'left'  => 'Left',
				'right' => 'Right',
			),
			'other_choice'      => 0,
			'save_other_choice' => 0,
			'default_value'     => '',
			'layout'            => 'horizontal',
			'allow_null'        => 0,
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_5638bfa1fa427',
			'label'             => 'Title',
			'name'              => 'title',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572a38b8946b1',
						'operator' => '==',
						'value'    => 'Title',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_5638bfe1fa428',
			'label'             => 'Text',
			'name'              => 'text',
			'type'              => 'wysiwyg',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572a38b8946b1',
						'operator' => '==',
						'value'    => 'Text',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'tabs'              => 'all',
			'toolbar'           => 'full',
			'media_upload'      => 1,
		),
		array(
			'key'               => 'field_5638c01afa42a',
			'label'             => 'Link Text',
			'name'              => 'link_text',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572a38b8946b1',
						'operator' => '==',
						'value'    => 'Link',
					),
				),
			),
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_57a0d872c7e66',
			'label'             => 'Link URL',
			'name'              => 'link_url',
			'type'              => 'page_link',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_572a38b8946b1',
						'operator' => '==',
						'value'    => 'Link',
					),
				),
			),
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'post_type'         => array(),
			'taxonomy'          => array(),
			'allow_null'        => 0,
			'multiple'          => 0,
			'allow_archives'    => 1,
		),
	),
	'min'        => '',
	'max'        => '',
];
$blurb_layout_args['sub_fields'][0]['key'] = 'field_blurb_label_label_color_name';
$blurb_layout_args['sub_fields'][1]['key'] = 'field_blurb_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Blurblist
——————————————————————————————————————————————————————————*/
#region Blurblist
$blurblist_layout_args                         = [
	'key'        => '5728deb2127ff',
	'name'       => 'layout_blurb_list',
	'label'      => 'Blurb List',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
		array(
			'key'               => 'field_5728deb212802',
			'label'             => 'Background Type',
			'name'              => 'background_type',
			'type'              => 'radio',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '33.333',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'None'  => 'None',
				'Image' => 'Image',
				'Color' => 'Color',
			),
			'other_choice'      => 0,
			'save_other_choice' => 0,
			'default_value'     => '',
			'layout'            => 'horizontal',
			'allow_null'        => 0,
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_5728dfda1280c',
			'label'             => 'Link Type',
			'name'              => 'link_type',
			'type'              => 'radio',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '33.333',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'Button'     => 'Button',
				'Background' => 'Background',
			),
			'other_choice'      => 0,
			'save_other_choice' => 0,
			'default_value'     => '',
			'layout'            => 'horizontal',
			'allow_null'        => 0,
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_5728e24da43fc',
			'label'             => 'Link Address',
			'name'              => 'link_location',
			'type'              => 'radio',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '33.333',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'Internal' => 'Internal',
				'External' => 'External',
			),
			'other_choice'      => 0,
			'save_other_choice' => 0,
			'default_value'     => '',
			'layout'            => 'horizontal',
			'allow_null'        => 0,
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_5728e0a01280e',
			'label'             => 'Elements',
			'name'              => 'elements',
			'type'              => 'select',
			'instructions'      => 'Control layout fields.',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'List Title'  => 'List Title',
				'List Intro'  => 'List Intro',
				'Blurb Image' => 'Blurb Image',
				'Blurb Title' => 'Blurb Title',
				'Blurb Text'  => 'Blurb Text',
				'Blurb Link'  => 'Blurb Link',
				'List Link'   => 'List Link',
			),
			'default_value'     => array(
				0 => 'List Title',
				1 => 'List Intro',
				2 => 'Blurb Image',
				3 => 'Blurb Title',
				4 => 'Blurb Text',
				5 => 'Blurb Link',
				6 => 'List Link',
			),
			'allow_null'        => 0,
			'multiple'          => 1,
			'ui'                => 1,
			'ajax'              => 0,
			'placeholder'       => '',
			'disabled'          => 0,
			'readonly'          => 0,
			'return_format'     => 'value',
		),
		array(
			'key'               => 'field_5728e4aab101b',
			'label'             => 'List Title',
			'name'              => 'list_title',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728e0a01280e',
						'operator' => '==',
						'value'    => 'List Title',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_572a3c29946b7',
			'label'             => 'List Intro',
			'name'              => 'list_intro',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728e0a01280e',
						'operator' => '==',
						'value'    => 'List Intro',
					),
				),
			),
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_5728e3f4bb82c',
			'label'             => 'Blurb Classes',
			'name'              => 'blurb_classes',
			'type'              => 'text',
			'instructions'      => 'Classes that are shared for each blurb (good for column classes).',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
		array(
			'key'               => 'field_5728ded612809',
			'label'             => 'Blurbs',
			'name'              => 'blurbs',
			'type'              => 'repeater',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'collapsed'         => 'field_5728eb648eebf',
			'min'               => '',
			'max'               => '',
			'layout'            => 'block',
			'button_label'      => 'Add Blurb',
			'sub_fields'        => array(
				array(
					'key'               => 'field_5728eb648eebf',
					'label'             => 'Label',
					'name'              => 'label',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_5728e15ffd5bb',
					'label'             => 'Foreground Image',
					'name'              => 'foreground_image',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5728e0a01280e',
								'operator' => '==',
								'value'    => 'Blurb Image',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'id',
					'preview_size'      => 'thumbnail',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_5728deb212803',
					'label'             => 'Title',
					'name'              => 'title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5728e0a01280e',
								'operator' => '==',
								'value'    => 'Blurb Title',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_5728deb212804',
					'label'             => 'Text',
					'name'              => 'text',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5728e0a01280e',
								'operator' => '==',
								'value'    => 'Blurb Text',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'full',
					'media_upload'      => 1,
				),
				array(
					'key'               => 'field_5728deb212805',
					'label'             => 'Link',
					'name'              => 'link',
					'type'              => 'url',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5728e0a01280e',
								'operator' => '==',
								'value'    => 'Blurb Link',
							),
							array(
								'field'    => 'field_5728e24da43fc',
								'operator' => '==',
								'value'    => 'External',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_5728e295a43fd',
					'label'             => 'Page Link',
					'name'              => 'page_link',
					'type'              => 'page_link',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5728e24da43fc',
								'operator' => '==',
								'value'    => 'Internal',
							),
							array(
								'field'    => 'field_5728e0a01280e',
								'operator' => '==',
								'value'    => 'Blurb Link',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'post_type'         => array(),
					'taxonomy'          => array(),
					'allow_null'        => 0,
					'multiple'          => 0,
					'allow_archives'    => 1,
				),
				array(
					'key'               => 'field_5728deb212806',
					'label'             => 'Link Text',
					'name'              => 'link_text',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5728dfda1280c',
								'operator' => '==',
								'value'    => 'Button',
							),
							array(
								'field'    => 'field_5728e0a01280e',
								'operator' => '==',
								'value'    => 'Blurb Link',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_5728deb212801',
					'label'             => 'Background Image',
					'name'              => 'background_image',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5728deb212802',
								'operator' => '==',
								'value'    => 'Image',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'id',
					'preview_size'      => 'thumbnail',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_5728e0811280d',
					'label'             => 'Background Color',
					'name'              => 'background_color',
					'type'              => 'color_picker',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_5728deb212802',
								'operator' => '==',
								'value'    => 'Color',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
				),
				array(
					'key'               => 'field_5728deb212807',
					'label'             => 'Classes',
					'name'              => 'class',
					'type'              => 'text',
					'instructions'      => 'Comma-separated list.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => 50,
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
				array(
					'key'               => 'field_5728deb212808',
					'label'             => 'ID',
					'name'              => 'id',
					'type'              => 'text',
					'instructions'      => 'One word only.',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => 50,
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
					'readonly'          => 0,
					'disabled'          => 0,
				),
			),
		),
		array(
			'key'               => 'field_5728ef26a58e1',
			'label'             => 'List Link',
			'name'              => 'list_link',
			'type'              => 'page_link',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728e0a01280e',
						'operator' => '==',
						'value'    => 'List Link',
					),
				),
			),
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'post_type'         => array(),
			'taxonomy'          => array(),
			'allow_null'        => 0,
			'multiple'          => 0,
			'allow_archives'    => 1,
		),
		array(
			'key'               => 'field_5728ef3aa58e2',
			'label'             => 'List Link Text',
			'name'              => 'list_link_text',
			'type'              => 'text',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => array(
				array(
					array(
						'field'    => 'field_5728e0a01280e',
						'operator' => '==',
						'value'    => 'List Link',
					),
				),
			),
			'wrapper'           => array(
				'width' => 50,
				'class' => '',
				'id'    => '',
			),
			'default_value'     => '',
			'placeholder'       => '',
			'prepend'           => '',
			'append'            => '',
			'maxlength'         => '',
			'readonly'          => 0,
			'disabled'          => 0,
		),
	),
	'min'        => '',
	'max'        => '',
];
$blurblist_layout_args['sub_fields'][0]['key'] = 'field_blurblist_label_label_color_name';
$blurblist_layout_args['sub_fields'][1]['key'] = 'field_blurblist_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Gallery
——————————————————————————————————————————————————————————*/
#region Gallery
$gallery_layout_args                         = [
	'key'        => '5638c3c0fa432',
	'name'       => 'layout_gallery',
	'label'      => 'Gallery',
	'display'    => 'block',
	'sub_fields' => array(
		$label_label_color_name_clone_args,
		$classes_id_clone_args,
		array(
			'key'               => 'field_5638c3c9fa433',
			'label'             => 'Images',
			'name'              => 'images',
			'type'              => 'gallery',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'min'               => '',
			'max'               => '',
			'preview_size'      => 'thumbnail',
			'library'           => 'all',
			'min_width'         => '',
			'min_height'        => '',
			'min_size'          => '',
			'max_width'         => '',
			'max_height'        => '',
			'max_size'          => '',
			'mime_types'        => '',
			'insert'            => 'append',
		),
		array(
			'key'               => 'field_577d56e09645b',
			'label'             => 'Image Size',
			'name'              => 'image_size',
			'type'              => 'select',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'choices'           => array(
				'large'  => 'Large',
				'medium' => 'Medium',
			),
			'default_value'     => array(
				'Large' => 'Large',
			),
			'allow_null'        => 0,
			'multiple'          => 0,
			'ui'                => 0,
			'ajax'              => 0,
			'placeholder'       => '',
			'disabled'          => 0,
			'readonly'          => 0,
			'return_format'     => 'value',
		),
	),
	'min'        => '',
	'max'        => '',
];
$gallery_layout_args['sub_fields'][0]['key'] = 'field_gallery_label_label_color_name';
$gallery_layout_args['sub_fields'][1]['key'] = 'field_gallery_classes_id';
#endregion

/*——————————————————————————————————————————————————————————
/  Filter Layouts
——————————————————————————————————————————————————————————*/
$layouts_arr = [
	'open_row'     => $open_row_layout_args,
	'close_row'    => $close_row_layout_args,
	'open_column'  => $open_column_layout_args,
	'close_column' => $close_column_layout_args,
	'content'      => $content_layout_args,
	'header'       => $header_layout_args,
	'slideshow'    => $slideshow_layout_args,
	'post_list'    => $post_list_layout_args,
	'map'          => $map_layout_args,
	'tabs'         => $tabs_layout_args,
	'blurb'        => $blurb_layout_args,
	'blurblist'    => $blurblist_layout_args,
	'gallery'      => $gallery_layout_args,
];
$layouts_arr = apply_filters( 'acf_flex_layouts_filter_layout_args', $layouts_arr );

acf_add_local_field_group( array(
	'key'                   => 'group_5790f5c9f0797',
	'title'                 => 'Flex Content',
	'fields'                => array(
		array(
			'key'               => 'field_layouts',
			'label'             => 'Layouts',
			'name'              => 'layouts',
			'type'              => 'flexible_content',
			'instructions'      => '',
			'required'          => 0,
			'conditional_logic' => 0,
			'wrapper'           => array(
				'width' => '',
				'class' => '',
				'id'    => '',
			),
			'button_label'      => 'Add Layout',
			'min'               => '',
			'max'               => '',
			'layouts'           => $layouts_arr,
		),
	),
	'location'              => array(
		array(
			array(
				'param'    => 'post_type',
				'operator' => '==',
				'value'    => 'page',
			),
		),
	),
	'menu_order'            => 0,
	'position'              => 'normal',
	'style'                 => 'default',
	'label_placement'       => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen'        => '',
	'active'                => 1,
	'description'           => '',
) );
